### ISSUE TITLE
domain name not replaced in webfinger request

### ISSUE THREAD

**Issue by YiffyToys** [sole/fedi-redi#1]
In the proxied webfinger request,
the domain name in the account name is not replaced with the domain-name of "redirect_to_server".

**Comment by sole** [comment]
Hi! sorry for the delay. Federating takes time 😆 
I think I vaguely understand what was happening. I was having some issues following users in another server and I fixed it with an `.htaccess` rule rather than relying on my naive proxying. If you still need this fixing, you can have a look at the latest version of the sample `.htaccess` file.
It isn't as neat but it also works, so I'll take working over neat!
Good luck and thanks for the tip! It was helpful in giving me a hint of what was wrong.
